CREATE OR REPLACE TABLE SIGNAL_EXTRACTION_DB.ANALYTICS.NEWS_ARTICLES_SENTIMENT_RANKED AS
WITH entity_day_sentiment AS (
    SELECT
        ENTITY_NAME,
        PUBLISHED_DATE,
        AVG(SENTIMENT_IMPACT_SCORE) AS avg_sis
    FROM SIGNAL_EXTRACTION_DB.STAGING.NEWS_ARTICLES_FEATURES
    GROUP BY ENTITY_NAME, PUBLISHED_DATE
),
ranked AS (
    SELECT
        naf.ARTICLE_ID,
        naf.ENTITY_NAME,
        naf.PUBLISHED_DATE,
        naf.SENTIMENT_IMPACT_SCORE,
        d.avg_sis,
        CASE
            WHEN d.avg_sis > 3 THEN
                ROW_NUMBER() OVER (PARTITION BY naf.ENTITY_NAME, naf.PUBLISHED_DATE -- Using ROWNUMBER() instead of RANK() to avoid same rank assignment
                             ORDER BY naf.SENTIMENT_IMPACT_SCORE DESC)
            WHEN d.avg_sis < 3 THEN
                ROW_NUMBER() OVER (PARTITION BY naf.ENTITY_NAME, naf.PUBLISHED_DATE
                             ORDER BY naf.SENTIMENT_IMPACT_SCORE ASC)
            ELSE
                ROW_NUMBER() OVER (PARTITION BY naf.ENTITY_NAME, naf.PUBLISHED_DATE
                             ORDER BY ABS(naf.SENTIMENT_IMPACT_SCORE - 3) DESC)
        END AS SENTIMENT_RANK
    FROM SIGNAL_EXTRACTION_DB.STAGING.NEWS_ARTICLES_FEATURES naf
    JOIN entity_day_sentiment d
      ON naf.PUBLISHED_DATE = d.PUBLISHED_DATE
     AND naf.ENTITY_NAME = d.ENTITY_NAME
),
ranked_top5 AS (
    SELECT
        ENTITY_NAME,
        PUBLISHED_DATE,
        avg_sis as AVG_SENTIMENT_IMPACT_SCORE,
        MAX(CASE WHEN SENTIMENT_RANK = 1 THEN ARTICLE_ID END) AS rank_1,
        MAX(CASE WHEN SENTIMENT_RANK = 2 THEN ARTICLE_ID END) AS rank_2,
        MAX(CASE WHEN SENTIMENT_RANK = 3 THEN ARTICLE_ID END) AS rank_3,
        MAX(CASE WHEN SENTIMENT_RANK = 4 THEN ARTICLE_ID END) AS rank_4,
        MAX(CASE WHEN SENTIMENT_RANK = 5 THEN ARTICLE_ID END) AS rank_5
    FROM ranked
    WHERE SENTIMENT_RANK <= 5
    GROUP BY ENTITY_NAME, PUBLISHED_DATE, avg_sis
)
SELECT *
FROM ranked_top5
ORDER BY ENTITY_NAME, PUBLISHED_DATE DESC;
