-- Setting Up: SIGNAL_EXTRACTION_DB.RAW.ARTICLE_ENTITY_MAP
USE DATABASE SIGNAL_EXTRACTION_DB;
USE SCHEMA RAW; 

CREATE TABLE IF NOT EXISTS SIGNAL_EXTRACTION_DB.RAW.ARTICLE_ENTITY_MAP (
    article_id STRING,
    q_value STRING,
    entity_name STRING,
    ingested_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);

-- Trucate & Delete
TRUNCATE TABLE SIGNAL_EXTRACTION_DB.RAW.ARTICLE_ENTITY_MAP;
DROP TABLE SIGNAL_EXTRACTION_DB.RAW.ARTICLE_ENTITY_MAP;